version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:8000"
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - ignatius-network

  webapp:
    build: ./webapp
    ports:
      - "8080:80"
    environment:
      - API_BASE_URL=http://localhost:5001/api/v1
    depends_on:
      - app
    networks:
      - ignatius-network

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ignatius_prod
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - ignatius-network

volumes:
  mongodb_data:

networks:
  ignatius-network:
    driver: bridge